### ISSUE TITLE
Build menu

### ISSUE THREAD

**Issue by alomoa** [ladyofcode/artifex-site#9]
- Menu should use the checkbox version to hide/unhide; (so it's navigable by keyboard)
- Menu should be responsive
- Menu will require dropdown menus

**Comment by alomoa** [comment]
9/9/2024
Desktop and mobile menu layout built. Created a breakpoint at width 1000px between the two.

What's left is to:
 - Add the hrefs to each nav menu item
 - Add animations
   - Hamburger (https://codepen.io/fabean/pen/XXegoQ)
   - submenu item transition for desktop and mobile

To confirm: @ladyofcode 
Can I assume the href will be the same as the nav item text?
  - upcoming => /upcoming
  - past jams -> /past-jams
  - jam 1 -> /past-jams/jam-1

**Comment by ladyofcode** [comment]
So the actual links will be:

Upcoming > /game-jam-2025
Past Jams > /past-jams
Contact > /contact

Jams links: /game-jam-2024, /game-jam-2023, etc

For Past Jams dropdown, either add the links manually or have it generate a link for every slug on the posts api route and use that array for the dropdown
